apiVersion: v1
kind: Service
metadata:
  name: service-2048
  namespace: "2048"
spec:
  type: NodePort
  selector:
    app: 2048pod
  ports:
  - port: 80 #service’in dışarıdan erişim için dinlediği port
    targetPort: 80 #Pod’un içinde çalışacak container’ın dinlediği porttur
    nodePort: 30080  #  NodePort’un cluster dışından erişim için kullanacağı port numarası 
    # 30000-32767 aralığında bir numara olmalıdır.
