apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: "{{ .Values.namespace }}"
  labels:
    name: {{ .Values.labels.projectname }}
type: Opaque
data:
  my_secret_game: {{ .Values.secret.data | quote }}
