apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: "{{ .Values.namespace }}"
  labels:
    name: {{ .Values.labels.projectname }}
spec: # kaynağın spesifikasyonları, nasıl çalışması gerektiği ve hangi özelliklere sahip olması gerektiği
  replicas: {{ .Values.replicas }}
  selector: # hangi podların bu deployment tarafından yönetileceği
    matchLabels: # label eşleşmesine göre yönetilecekleri belirler
      app: {{ .Values.labels.app }} # dosyanın yöneteceği etiket
  template: # podların bilgileri
    metadata:
      labels: # burada matchlabels'deki etiket olmalı ki yönetilsin
         app: {{ .Values.labels.app }} 
         name: {{ .Values.labels.projectname }}
    spec: # podların spesifikasyonları
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.port }}  # Pod'un dinleyeceği port
        env:
        - name: {{ .Values.env.name }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}  # Secret'ın metadatadaki adı
              key: my_secret_game  # Secret içindeki data
