apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: "{{ .Values.namespace }}"
spec:
  type: NodePort
  selector:
    app: {{ .Values.labels.app }}
  ports:
  - port: {{ .Values.service.port }} #service’in dışarıdan erişim için dinlediği port
    targetPort: {{ .Values.service.targetPort }} #Pod’un içinde çalışacak container’ın dinlediği porttur
    nodePort: {{ .Values.service.nodePort }}  #  NodePort’un cluster dışından erişim için kullanacağı port numarası 
    # 30000-32767 aralığında bir numara olmalıdır.
